// This file will be generated by Supabase CLI or manually created
// For now, we'll use a basic type that matches our schema

export interface Database {
  public: {
    Tables: {
      restaurants: {
        Row: {
          id: string;
          name: string;
          slug: string;
          email: string;
          phone: string | null;
          address: string | null;
          subscription_status: string;
          owner_id: string;
          created_at: string;
          updated_at: string;
        };
        Insert: Omit<Database['public']['Tables']['restaurants']['Row'], 'id' | 'created_at' | 'updated_at'>;
        Update: Partial<Database['public']['Tables']['restaurants']['Insert']>;
      };
      restaurant_staff: {
        Row: {
          id: string;
          restaurant_id: string;
          user_id: string;
          role: string;
          display_name: string;
          is_active: boolean;
          permissions: any;
          created_at: string;
        };
        Insert: Omit<Database['public']['Tables']['restaurant_staff']['Row'], 'id' | 'created_at'>;
        Update: Partial<Database['public']['Tables']['restaurant_staff']['Insert']>;
      };
      kitchen_stations: {
        Row: {
          id: string;
          restaurant_id: string;
          station_name: string;
          station_type: string;
          is_active: boolean;
          position_order: number;
          created_at: string;
        };
        Insert: Omit<Database['public']['Tables']['kitchen_stations']['Row'], 'id' | 'created_at'>;
        Update: Partial<Database['public']['Tables']['kitchen_stations']['Insert']>;
      };
      active_sessions: {
        Row: {
          id: string;
          user_id: string;
          restaurant_id: string;
          station_id: string | null;
          session_token: string;
          user_name: string | null;
          status: string;
          device_info: any;
          last_seen: string;
          created_at: string;
        };
        Insert: Omit<Database['public']['Tables']['active_sessions']['Row'], 'id' | 'created_at'>;
        Update: Partial<Database['public']['Tables']['active_sessions']['Insert']>;
      };
      restaurant_tables: {
        Row: {
          id: string;
          restaurant_id: string;
          table_number: number;
          qr_token: string;
          is_active: boolean;
          created_at: string;
        };
        Insert: Omit<Database['public']['Tables']['restaurant_tables']['Row'], 'id' | 'created_at'>;
        Update: Partial<Database['public']['Tables']['restaurant_tables']['Insert']>;
      };
      menu_categories: {
        Row: {
          id: string;
          restaurant_id: string;
          name: string;
          sort_order: number;
          is_active: boolean;
          created_at: string;
        };
        Insert: Omit<Database['public']['Tables']['menu_categories']['Row'], 'id' | 'created_at'>;
        Update: Partial<Database['public']['Tables']['menu_categories']['Insert']>;
      };
      menu_items: {
        Row: {
          id: string;
          restaurant_id: string;
          category_id: string;
          name: string;
          description: string | null;
          price: number;
          image_url: string | null;
          is_available: boolean;
          sort_order: number;
          preferred_station_id: string | null;
          preparation_time_minutes: number;
          created_at: string;
          updated_at: string;
        };
        Insert: Omit<Database['public']['Tables']['menu_items']['Row'], 'id' | 'created_at' | 'updated_at'>;
        Update: Partial<Database['public']['Tables']['menu_items']['Insert']>;
      };
      orders: {
        Row: {
          id: string;
          restaurant_id: string;
          table_id: string;
          order_number: string;
          status: string;
          total_amount: number;
          special_instructions: string | null;
          customer_name: string | null;
          claimed_by: string | null;
          claimed_at: string | null;
          priority: number;
          estimated_time_minutes: number;
          assigned_station_id: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: Omit<Database['public']['Tables']['orders']['Row'], 'id' | 'created_at' | 'updated_at'>;
        Update: Partial<Database['public']['Tables']['orders']['Insert']>;
      };
      order_items: {
        Row: {
          id: string;
          order_id: string;
          menu_item_id: string;
          quantity: number;
          unit_price: number;
          special_instructions: string | null;
          item_status: string;
          started_at: string | null;
          completed_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: Omit<Database['public']['Tables']['order_items']['Row'], 'id' | 'created_at' | 'updated_at'>;
        Update: Partial<Database['public']['Tables']['order_items']['Insert']>;
      };
    };
    Views: {
      [_ in never]: never;
    };
    Functions: {
      claim_order: {
        Args: {
          order_uuid: string;
          session_uuid: string;
        };
        Returns: boolean;
      };
      release_order: {
        Args: {
          order_uuid: string;
          session_uuid: string;
        };
        Returns: boolean;
      };
    };
    Enums: {
      user_role: 'owner' | 'manager' | 'chef' | 'server' | 'host';
    };
  };
} 